avator_1:
  preparation: False  # ставь False, если уже есть landmarks/данные
  bbox_shift: 5
  fps: 5
  batch_size: 16
  image_resolution: 128
  video_path: "data/video/52525.mp4"
  audio_clips:
    audio_0: "data/audio/sun.wav"
  